server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/apiworklink_dev?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

jwt.secret=bXLjbGF2ZXN1cGVyc2VjcmV0YW15bGFyZ2Fqd3QxMjM0NTY3ODkw
jwt.expiration=86400000

spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.orm.connections.pooling=warn
logging.level.org.hibernate.tool.hbm2ddl=warn