server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.datasource.url=jdbc:mariadb://localhost:3307/APIworkLink_dev?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

jwt.secret=bXljbGF2ZXN1cGVyc2VjcmV0YW15bGFyZ2Fqd3QxMjM0NTY3ODkw
jwt.expiration=86400000

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.connections.pooling=info
logging.level.org.hibernate.tool.hbm2ddl=debug